### ISSUE TITLE
mvn package does not pass test phase

### ISSUE THREAD

**Issue by jandegithub** [opengeospatial/ets-ogcapi-edr10#137]
**Describe the bug**
Test phase of the build does not succeed.

**To Reproduce**
1. mvn package
2. Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.02 sec <<< FAILURE! - in org.opengis.cite.ogcapiedr10.VerifySuiteFixtureListener
org.opengis.cite.ogcapiedr10.VerifySuiteFixtureListener  Time elapsed: 0.02 sec  <<< ERROR!
java.lang.ExceptionInInitializerError
        at org.opengis.cite.ogcapiedr10.VerifySuiteFixtureListener.setUpClass(VerifySuiteFixtureListener.java:23)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @209face7
        at org.opengis.cite.ogcapiedr10.VerifySuiteFixtureListener.setUpClass(VerifySuiteFixtureListener.java:23)

**Expected behavior**
tests to pass

**Screenshots**

**Additional context**
CentOS Linux release 7.7.1908

java version "17.0.11" 2024-04-16 LTS
Java(TM) SE Runtime Environment (build 17.0.11+7-LTS-207)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.11+7-LTS-207, mixed mode, sharing)
/usr/lib/jvm/jdk-17-oracle-x64/bin/java

Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
Maven home: /usr/lib/jvm/apache-maven-3.9.9
Java version: 17.0.11, vendor: Oracle Corporation, runtime: /usr/lib/jvm/jdk-17-oracle-x64
Default locale: en_US, platform encoding: UTF-8

**Comment by dstenger** [comment]
Thank you for reporting.

Currently, the test suites require Java 8.
However, we are in the progress to migrate to Java 17.
Can you please check if switching to Java 8 solves your problem?
